/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package locadora.views;

import javax.swing.JOptionPane;

/**
 *
 * @author Aluno
 */
public class MainScreen extends javax.swing.JFrame {

    /**
     * Creates new form MainScreen
     */
    public MainScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        query1 = java.beans.Beans.isDesignTime() ? null : ((javax.persistence.EntityManager)null).createQuery("");
        jPanel2 = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jMenuMainScreen = new javax.swing.JMenuBar();
        jMenuRental = new javax.swing.JMenu();
        jMenuItemRental = new javax.swing.JMenuItem();
        jMenuItemConsult = new javax.swing.JMenuItem();
        jMenuCadastro = new javax.swing.JMenu();
        jMenuItemActor = new javax.swing.JMenuItem();
        jMenuItemClient = new javax.swing.JMenuItem();
        jMenuItemFilm = new javax.swing.JMenuItem();
        jMenuItem = new javax.swing.JMenuItem();
        jMenuClose = new javax.swing.JMenu();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Video Locadora Hora da Pipoca");
        setResizable(false);

        jMenuRental.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon.png"))); // NOI18N
        jMenuRental.setText("Locação");
        jMenuRental.setFont(new java.awt.Font("MV Boli", 0, 36)); // NOI18N

        jMenuItemRental.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        jMenuItemRental.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/seta.png"))); // NOI18N
        jMenuItemRental.setText("Alugar");
        jMenuRental.add(jMenuItemRental);

        jMenuItemConsult.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        jMenuItemConsult.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/seta.png"))); // NOI18N
        jMenuItemConsult.setText("Consultar");
        jMenuItemConsult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsultActionPerformed(evt);
            }
        });
        jMenuRental.add(jMenuItemConsult);

        jMenuMainScreen.add(jMenuRental);

        jMenuCadastro.setText("Cadastro");
        jMenuCadastro.setFont(new java.awt.Font("MV Boli", 0, 36)); // NOI18N

        jMenuItemActor.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        jMenuItemActor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/seta.png"))); // NOI18N
        jMenuItemActor.setText("Ator");
        jMenuItemActor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemActorActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemActor);

        jMenuItemClient.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        jMenuItemClient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/seta.png"))); // NOI18N
        jMenuItemClient.setText("Cliente");
        jMenuCadastro.add(jMenuItemClient);

        jMenuItemFilm.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        jMenuItemFilm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/seta.png"))); // NOI18N
        jMenuItemFilm.setText("Filme");
        jMenuItemFilm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFilmActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemFilm);

        jMenuItem.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        jMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/seta.png"))); // NOI18N
        jMenuItem.setText("Item");
        jMenuCadastro.add(jMenuItem);

        jMenuMainScreen.add(jMenuCadastro);

        jMenuClose.setText("Sair");
        jMenuClose.setFont(new java.awt.Font("MV Boli", 0, 36)); // NOI18N
        jMenuMainScreen.add(jMenuClose);

        setJMenuBar(jMenuMainScreen);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 819, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 482, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(841, 598));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemConsultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsultActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemConsultActionPerformed

    private void jMenuItemFilmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFilmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemFilmActionPerformed

    private void jMenuItemActorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemActorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemActorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
           try{
                new MainScreen().setVisible(true);
           }catch(NullPointerException e){
               System.out.println(e.getMessage());
           } 
           }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenuCadastro;
    private javax.swing.JMenu jMenuClose;
    private javax.swing.JMenuItem jMenuItem;
    private javax.swing.JMenuItem jMenuItemActor;
    private javax.swing.JMenuItem jMenuItemClient;
    private javax.swing.JMenuItem jMenuItemConsult;
    private javax.swing.JMenuItem jMenuItemFilm;
    private javax.swing.JMenuItem jMenuItemRental;
    private javax.swing.JMenuBar jMenuMainScreen;
    private javax.swing.JMenu jMenuRental;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.persistence.Query query1;
    // End of variables declaration//GEN-END:variables
}
