/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package locadora.views;

import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import locadora.controller.ActorController;
import locadora.dao.ExceptionDAO;
import locadora.model.Actor;

/**
 *
 * @author Aluno
 */
public class ScreenConsultActor extends javax.swing.JFrame {

    private ScreenActor screenActor;
    /**
     * Creates new form ScreenConsultActor
     */
    public ScreenConsultActor() {
        initComponents();
    }
    
    public ScreenConsultActor(ScreenActor screenActor){
        this.screenActor = screenActor;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelConsultActor = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableConsultActor = new javax.swing.JTable();
        jLabelNameActor = new javax.swing.JLabel();
        jTextFieldNameActor = new javax.swing.JTextField();
        jButtonCunsultActor = new javax.swing.JButton();
        jLabelConsutActor = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                fecharJanela(evt);
            }
        });

        jPanelConsultActor.setBackground(new java.awt.Color(153, 153, 153));
        jPanelConsultActor.setPreferredSize(new java.awt.Dimension(500, 400));

        jTableConsultActor.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jTableConsultActor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Nacionalidade"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableConsultActor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableConsultActorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableConsultActor);

        jLabelNameActor.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabelNameActor.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNameActor.setText("Informe o nome do actor:");

        jTextFieldNameActor.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jTextFieldNameActor.setToolTipText("informe o nome do actor para consulta");

        jButtonCunsultActor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/lupa.png"))); // NOI18N
        jButtonCunsultActor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultar(evt);
            }
        });

        javax.swing.GroupLayout jPanelConsultActorLayout = new javax.swing.GroupLayout(jPanelConsultActor);
        jPanelConsultActor.setLayout(jPanelConsultActorLayout);
        jPanelConsultActorLayout.setHorizontalGroup(
            jPanelConsultActorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConsultActorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelNameActor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldNameActor, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCunsultActor, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelConsultActorLayout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 696, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        jPanelConsultActorLayout.setVerticalGroup(
            jPanelConsultActorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelConsultActorLayout.createSequentialGroup()
                .addGroup(jPanelConsultActorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelConsultActorLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanelConsultActorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelNameActor)
                            .addComponent(jTextFieldNameActor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelConsultActorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonCunsultActor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        jLabelConsutActor.setFont(new java.awt.Font("MV Boli", 0, 36)); // NOI18N
        jLabelConsutActor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon.png"))); // NOI18N
        jLabelConsutActor.setText("Consultar Actor");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addComponent(jLabelConsutActor))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jPanelConsultActor, javax.swing.GroupLayout.PREFERRED_SIZE, 758, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabelConsutActor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelConsultActor, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void consultar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultar
       
        String name = jTextFieldNameActor.getText();
        DefaultTableModel tableModel = (DefaultTableModel) jTableConsultActor.getModel();
        tableModel.setRowCount(0);
        ActorController actorController = new ActorController();
        
        try{
            ArrayList<Actor> actors = actorController.consultActor(name);
            actors.forEach((Actor actor) -> {
                tableModel.addRow(new Object[] { 
                                                actor.getCodctor(),
                                                actor.getName(),
                                                actor.getNationality()
                                            });
            });
            jTableConsultActor.setModel(tableModel);
        }catch(ExceptionDAO e){
            Logger.getLogger(Actor.class.getName()).log(Level.SEVERE, null, e);
        }
        
        
        
        
        
        
    }//GEN-LAST:event_consultar

    private void fecharJanela(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_fecharJanela
        dispose();
        this.screenActor.setVisible(true);
    }//GEN-LAST:event_fecharJanela

    private void jTableConsultActorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableConsultActorMouseClicked

        if(evt.getClickCount()==2){
            Integer codActor = (Integer) jTableConsultActor.getModel().getValueAt(jTableConsultActor.getSelectedRow(), 0);
            String name = (String) jTableConsultActor.getModel().getValueAt(jTableConsultActor.getSelectedRow(), 1);
            String nationality = (String) jTableConsultActor.getModel().getValueAt(jTableConsultActor.getSelectedRow(), 2);
            
            this.screenActor.buscarActor(codActor, name, nationality);
            this.screenActor.setVisible(true);
            this.dispose();
            
        }
    }//GEN-LAST:event_jTableConsultActorMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ScreenConsultActor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ScreenConsultActor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ScreenConsultActor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ScreenConsultActor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ScreenConsultActor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCunsultActor;
    private javax.swing.JLabel jLabelConsutActor;
    private javax.swing.JLabel jLabelNameActor;
    private javax.swing.JPanel jPanelConsultActor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableConsultActor;
    private javax.swing.JTextField jTextFieldNameActor;
    // End of variables declaration//GEN-END:variables
}
