/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package locadora.views;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import locadora.controller.ClientController;
import locadora.dao.ExceptionDAO;

/**
 *
 * @author Ernesto.Castro
 */
public class ScreenClient extends javax.swing.JFrame {
    private Integer codClient = 0;
    private TelaPrincipal telaPrincipal;
    /**
     * Creates new form ScreenClient
     */
    public ScreenClient() {
        initComponents();
    }
    
    public ScreenClient(TelaPrincipal telaPricipal) {
        this.telaPrincipal = telaPricipal;
        initComponents();
    }
    public void buscarClient(Integer codClient, String name, String nif, String email, String address, Date dtBirth){
        this.codClient = codClient;
        this.jTextFieldName.setText(name);
        this.jFormattedTextFiedNif.setText(nif);
        this.jTextFieldEmail.setText(email);
        this.jTextFieldAddress.setText(address);
        SimpleDateFormat mask = new SimpleDateFormat("dd/MM/yyyy");
        this.jFormattedTextFieldDtBirth.setText(mask.format(dtBirth));
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelCadastrClient = new javax.swing.JLabel();
        jPanelCadastClient = new javax.swing.JPanel();
        jLabelName = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jLabelDtBirth = new javax.swing.JLabel();
        jFormattedTextFieldDtBirth = new javax.swing.JFormattedTextField();
        jLabelNIF = new javax.swing.JLabel();
        jFormattedTextFiedNif = new javax.swing.JFormattedTextField();
        jLabelEmail = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabelAddress = new javax.swing.JLabel();
        jTextFieldAddress = new javax.swing.JTextField();
        jButtonSaveClient = new javax.swing.JButton();
        jButtonCleanClient = new javax.swing.JButton();
        jButtonCancelClient = new javax.swing.JButton();
        jButtonConsultClient = new javax.swing.JButton();
        jButtonDeleteClient = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Video Locadora Hora da Pipoca");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                fechar(evt);
            }
        });

        jLabelCadastrClient.setFont(new java.awt.Font("MV Boli", 0, 36)); // NOI18N
        jLabelCadastrClient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon.png"))); // NOI18N
        jLabelCadastrClient.setText("CADASTRO DE CLIENTE");

        jPanelCadastClient.setBackground(new java.awt.Color(153, 153, 153));
        jPanelCadastClient.setPreferredSize(new java.awt.Dimension(758, 500));

        jLabelName.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabelName.setForeground(new java.awt.Color(255, 255, 255));
        jLabelName.setText("Nome:");

        jTextFieldName.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jTextFieldName.setToolTipText("Nome do cliente");

        jLabelDtBirth.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabelDtBirth.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDtBirth.setText("Data de Nascimento:");

        try {
            jFormattedTextFieldDtBirth.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldDtBirth.setToolTipText("Digite aqui a data");
        jFormattedTextFieldDtBirth.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        jLabelNIF.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabelNIF.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNIF.setText("NIF:");

        try {
            jFormattedTextFiedNif.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-###-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFiedNif.setToolTipText("Número de identificação fiscal");
        jFormattedTextFiedNif.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N

        jLabelEmail.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabelEmail.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEmail.setText("E-mail:");
        jLabelEmail.setToolTipText("");

        jTextFieldEmail.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jTextFieldEmail.setToolTipText("E-mail do cliente");

        jLabelAddress.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabelAddress.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAddress.setText("Endereço:");

        jTextFieldAddress.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jTextFieldAddress.setToolTipText("Informe o endereço do cliente");

        jButtonSaveClient.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonSaveClient.setText("Salvar");
        jButtonSaveClient.setToolTipText("");
        jButtonSaveClient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveClient(evt);
            }
        });

        jButtonCleanClient.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonCleanClient.setText("Limpar");
        jButtonCleanClient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CleanClient(evt);
            }
        });
        jButtonCleanClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparCliente(evt);
            }
        });

        jButtonCancelClient.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonCancelClient.setText("Cancelar");
        jButtonCancelClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelClientActionPerformed(evt);
            }
        });

        jButtonConsultClient.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonConsultClient.setText("Consultar");
        jButtonConsultClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrir_telaConsultClient(evt);
            }
        });

        jButtonDeleteClient.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonDeleteClient.setText("Apagar");
        jButtonDeleteClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apagarCliente(evt);
            }
        });

        javax.swing.GroupLayout jPanelCadastClientLayout = new javax.swing.GroupLayout(jPanelCadastClient);
        jPanelCadastClient.setLayout(jPanelCadastClientLayout);
        jPanelCadastClientLayout.setHorizontalGroup(
            jPanelCadastClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastClientLayout.createSequentialGroup()
                .addGroup(jPanelCadastClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCadastClientLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(jPanelCadastClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelCadastClientLayout.createSequentialGroup()
                                .addComponent(jLabelDtBirth)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFormattedTextFieldDtBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelCadastClientLayout.createSequentialGroup()
                                .addComponent(jLabelName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelCadastClientLayout.createSequentialGroup()
                                .addComponent(jLabelNIF)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFormattedTextFiedNif, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanelCadastClientLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(jPanelCadastClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelCadastClientLayout.createSequentialGroup()
                                .addComponent(jButtonSaveClient)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonCleanClient)
                                .addGap(31, 31, 31)
                                .addComponent(jButtonDeleteClient)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonCancelClient)
                                .addGap(33, 33, 33)
                                .addComponent(jButtonConsultClient))
                            .addGroup(jPanelCadastClientLayout.createSequentialGroup()
                                .addComponent(jLabelAddress)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelCadastClientLayout.createSequentialGroup()
                                .addComponent(jLabelEmail)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        jPanelCadastClientLayout.setVerticalGroup(
            jPanelCadastClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastClientLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanelCadastClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelName)
                    .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanelCadastClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDtBirth)
                    .addComponent(jFormattedTextFieldDtBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanelCadastClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNIF)
                    .addComponent(jFormattedTextFiedNif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jPanelCadastClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEmail)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanelCadastClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelAddress)
                    .addComponent(jTextFieldAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanelCadastClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonConsultClient)
                    .addComponent(jButtonCancelClient)
                    .addComponent(jButtonCleanClient)
                    .addComponent(jButtonSaveClient)
                    .addComponent(jButtonDeleteClient))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addComponent(jLabelCadastrClient)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelCadastClient, javax.swing.GroupLayout.DEFAULT_SIZE, 813, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabelCadastrClient)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelCadastClient, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void saveClient(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveClient
       boolean success;
       
       try{
           ClientController clientController = new ClientController();
           if(codClient == 0){
                success = clientController.cadastrarClient(jTextFieldName.getText(), jFormattedTextFiedNif.getText(), jTextFieldEmail.getText(), 
                jTextFieldAddress.getText(), jFormattedTextFieldDtBirth.getText());
           } else {
               success = clientController.updateClient(codClient, jTextFieldName.getText(), jFormattedTextFiedNif.getText(), jTextFieldEmail.getText(), 
               jTextFieldAddress.getText(), jFormattedTextFieldDtBirth.getText());
           }
           if(success){
               JOptionPane.showMessageDialog(null, "O cadastro foi realizado com sucesso!");
               this.CleanClient(evt);
           } else {
               JOptionPane.showMessageDialog(null, "Os campos não foram preenchidos corretamente.");
           }
        }catch(Exception ex){
           JOptionPane.showMessageDialog(null, "ERRO: " + ex.getMessage());
        }
    }//GEN-LAST:event_saveClient

    private void CleanClient(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CleanClient
        jTextFieldName.setText("");
        jFormattedTextFieldDtBirth.setText("");
        jTextFieldEmail.setText("");
        jTextFieldAddress.setText("");
        jFormattedTextFiedNif.setText("");
    }//GEN-LAST:event_CleanClient

    private void abrir_telaConsultClient(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrir_telaConsultClient
    ScreenConsultClient teleConsulta = new ScreenConsultClient(this);
    this.setVisible(false);
    teleConsulta.setVisible(true);
       
    }//GEN-LAST:event_abrir_telaConsultClient

    private void apagarCliente(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apagarCliente

        boolean success;
        ClientController clientController = new ClientController();
       
        try {
            success = clientController.deleteClient(codClient);
            if(success){
                JOptionPane.showMessageDialog(null, "Client apagado com sucesso!");
                this.limparCliente(evt);
            } else
                JOptionPane.showMessageDialog(null, "[ERRO] ao apagar cliente, nenhum cliente selecionado.");
        } catch (ExceptionDAO ex) {
            Logger.getLogger(ScreenClient.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_apagarCliente

    private void limparCliente(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparCliente
        jTextFieldName.setText("");
        jFormattedTextFieldDtBirth.setText("");
        jTextFieldEmail.setText("");
        jTextFieldAddress.setText("");
        jFormattedTextFiedNif.setText("");
    }//GEN-LAST:event_limparCliente

    private void jButtonCancelClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelClientActionPerformed

       this.dispose();
       this.telaPrincipal.setVisible(true);
    }//GEN-LAST:event_jButtonCancelClientActionPerformed

    private void fechar(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_fechar

        this.dispose();
        this.telaPrincipal.setVisible(true);
       
    }//GEN-LAST:event_fechar

    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ScreenClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ScreenClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ScreenClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ScreenClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ScreenClient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelClient;
    private javax.swing.JButton jButtonCleanClient;
    private javax.swing.JButton jButtonConsultClient;
    private javax.swing.JButton jButtonDeleteClient;
    private javax.swing.JButton jButtonSaveClient;
    private javax.swing.JFormattedTextField jFormattedTextFiedNif;
    private javax.swing.JFormattedTextField jFormattedTextFieldDtBirth;
    private javax.swing.JLabel jLabelAddress;
    private javax.swing.JLabel jLabelCadastrClient;
    private javax.swing.JLabel jLabelDtBirth;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelNIF;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JPanel jPanelCadastClient;
    private javax.swing.JTextField jTextFieldAddress;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldName;
    // End of variables declaration//GEN-END:variables
}
