/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package locadora.views;


import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import locadora.controller.FilmController;
import locadora.dao.ExceptionDAO;
import locadora.model.Film;

/**
 *
 * @author Ernesto.Castro
 */
public class ScreenConsultFilm extends javax.swing.JFrame {

    private JFrame telaCadastro;
    /**
     * Creates new form ScreenConsultFilm
     */
    public ScreenConsultFilm() {
        initComponents();
    }
    
    public ScreenConsultFilm(JFrame screenFilm){
        this.telaCadastro = screenFilm;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelScreenCunsultFilm = new javax.swing.JPanel();
        jLabelTitleFilme = new javax.swing.JLabel();
        jTextFieldTitleFilm = new javax.swing.JTextField();
        jButtonConsultFilm = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableConsultFilm = new javax.swing.JTable();
        jLabelConsulFilm = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                fecharTela(evt);
            }
        });

        jPanelScreenCunsultFilm.setBackground(new java.awt.Color(153, 153, 153));
        jPanelScreenCunsultFilm.setPreferredSize(new java.awt.Dimension(600, 400));

        jLabelTitleFilme.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabelTitleFilme.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitleFilme.setText("Informe o titulo do filme:");

        jTextFieldTitleFilm.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jTextFieldTitleFilm.setToolTipText("Informe o nome do filme que deseja consultar");

        jButtonConsultFilm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/lupa.png"))); // NOI18N
        jButtonConsultFilm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultFilm(evt);
            }
        });

        jTableConsultFilm.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jTableConsultFilm.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código ", "Titúlo", "Gênero", "Sinopse", "Duração"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableConsultFilm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableConsultFilmMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableConsultFilm);

        javax.swing.GroupLayout jPanelScreenCunsultFilmLayout = new javax.swing.GroupLayout(jPanelScreenCunsultFilm);
        jPanelScreenCunsultFilm.setLayout(jPanelScreenCunsultFilmLayout);
        jPanelScreenCunsultFilmLayout.setHorizontalGroup(
            jPanelScreenCunsultFilmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelScreenCunsultFilmLayout.createSequentialGroup()
                .addGroup(jPanelScreenCunsultFilmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelScreenCunsultFilmLayout.createSequentialGroup()
                        .addContainerGap(35, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 665, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelScreenCunsultFilmLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabelTitleFilme)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldTitleFilm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonConsultFilm, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(44, 44, 44))
        );
        jPanelScreenCunsultFilmLayout.setVerticalGroup(
            jPanelScreenCunsultFilmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelScreenCunsultFilmLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanelScreenCunsultFilmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonConsultFilm, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelScreenCunsultFilmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelTitleFilme)
                        .addComponent(jTextFieldTitleFilm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabelConsulFilm.setFont(new java.awt.Font("MV Boli", 0, 36)); // NOI18N
        jLabelConsulFilm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon.png"))); // NOI18N
        jLabelConsulFilm.setText("Consultar Filme");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(229, 229, 229)
                .addComponent(jLabelConsulFilm)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jPanelScreenCunsultFilm, javax.swing.GroupLayout.DEFAULT_SIZE, 744, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelConsulFilm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelScreenCunsultFilm, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void consultFilm(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultFilm
        String nome = jTextFieldTitleFilm.getText();
        DefaultTableModel tableModel = (DefaultTableModel) jTableConsultFilm.getModel();
        tableModel.setRowCount(0);
        FilmController filmController = new FilmController();
        
        try{
            ArrayList<Film> filmes = filmController.consultFilm(nome);
            filmes.forEach((Film film) -> {
                tableModel.addRow(new Object[] {film.getCodFilm(),
                                                film.getTitle(),
                                                film.getGender(),
                                                film.getSynopsis(),
                                                film.getDuration()});
                    
            });
                jTableConsultFilm.setModel(tableModel);
        }catch(ExceptionDAO e){
               Logger.getLogger(ScreenFilm.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_consultFilm

    private void fecharTela(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_fecharTela
        this.dispose();
        this.setVisible(false);
        telaCadastro.setVisible(true);
        
    }//GEN-LAST:event_fecharTela

    private void jTableConsultFilmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableConsultFilmMouseClicked
        
        if(evt.getClickCount()==2){
            Integer codFilm = (Integer) jTableConsultFilm.getModel().getValueAt(jTableConsultFilm.getSelectedRow(), 0);
            String title = (String ) jTableConsultFilm.getModel().getValueAt(jTableConsultFilm.getSelectedRow(), 1);
            String gender = (String) jTableConsultFilm.getModel().getValueAt(jTableConsultFilm.getSelectedRow(), 2);
            String synopsis = (String) jTableConsultFilm.getModel().getValueAt(jTableConsultFilm.getSelectedRow(), 3);
            Integer duration = (Integer)jTableConsultFilm.getModel().getValueAt(jTableConsultFilm.getSelectedRow(), 4);
            
            
            String tipoTela = this.telaCadastro.getClass().getSimpleName();
            if(tipoTela.equals("ScreenFilm")){
            ScreenFilm telaCadastroFilme = (ScreenFilm) this.telaCadastro;
            telaCadastroFilme.buscarFilm(codFilm, title, gender, synopsis, duration);
            telaCadastroFilme.setVisible(true);
            } else {
                ScreenItem telaCadastroItem = (ScreenItem) this.telaCadastro;
                telaCadastroItem.buscarFilme(codFilm, title);
                telaCadastroItem.setVisible(true);
            }
            this.dispose();   
        } 
        
    }//GEN-LAST:event_jTableConsultFilmMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ScreenConsultFilm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ScreenConsultFilm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ScreenConsultFilm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ScreenConsultFilm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ScreenConsultFilm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConsultFilm;
    private javax.swing.JLabel jLabelConsulFilm;
    private javax.swing.JLabel jLabelTitleFilme;
    private javax.swing.JPanel jPanelScreenCunsultFilm;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableConsultFilm;
    private javax.swing.JTextField jTextFieldTitleFilm;
    // End of variables declaration//GEN-END:variables
}
