/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package locadora.views;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import locadora.controller.ItemController;
import locadora.dao.ExceptionDAO;

/**
 *
 * @author Ernesto.Castro
 */
public class ScreenItem extends javax.swing.JFrame {

    private Integer codFilm = 0;
    private TelaPrincipal telaPrincipal;
    /**
     * Creates new form ScreenItem
     */
    public ScreenItem() {
        initComponents();
    }
    
    
    public ScreenItem(TelaPrincipal telaPrincipal) {
        this.telaPrincipal = telaPrincipal;
        initComponents();
    }
    
    public void buscarFilme(Integer codFilme, String title){
        this.codFilm = codFilme;
        this.jTextFieldTitleItem.setText(title);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelCadastItem = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        jPanelCadastItem = new javax.swing.JPanel();
        jLabelTitle = new javax.swing.JLabel();
        jTextFieldTitleItem = new javax.swing.JTextField();
        jButtonConsultFilm = new javax.swing.JButton();
        jLabelType = new javax.swing.JLabel();
        jComboBoxType = new javax.swing.JComboBox<>();
        jLabelPrice = new javax.swing.JLabel();
        jTextFieldPrice = new javax.swing.JTextField();
        jButtonSaveItem = new javax.swing.JButton();
        jButtonCleanItem = new javax.swing.JButton();
        jButtonCancelItem = new javax.swing.JButton();
        jButtonConsultItem = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Video Locadora Hora da Pipoca");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                fechar(evt);
            }
        });

        jLabelCadastItem.setFont(new java.awt.Font("MV Boli", 0, 36)); // NOI18N
        jLabelCadastItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon.png"))); // NOI18N
        jLabelCadastItem.setText("CADASTRO DE ITEM");

        jPanelCadastItem.setBackground(new java.awt.Color(102, 102, 102));
        jPanelCadastItem.setPreferredSize(new java.awt.Dimension(758, 500));

        jLabelTitle.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitle.setText("Titúlo:");

        jTextFieldTitleItem.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jTextFieldTitleItem.setToolTipText("Titúlo do Item");

        jButtonConsultFilm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/lupa.png"))); // NOI18N
        jButtonConsultFilm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultFilmActionPerformed(evt);
            }
        });

        jLabelType.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabelType.setForeground(new java.awt.Color(255, 255, 255));
        jLabelType.setText("Tipo:");

        jComboBoxType.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jComboBoxType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione um tipo", "Blu-Ray", "Disc", "CD", "DVD" }));
        jComboBoxType.setToolTipText("Escolhe em tipo de formato");

        jLabelPrice.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabelPrice.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPrice.setText("Preço:");

        jTextFieldPrice.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jTextFieldPrice.setToolTipText("Informe o preço");

        jButtonSaveItem.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonSaveItem.setText("Salvar");
        jButtonSaveItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveItemActionPerformed(evt);
            }
        });

        jButtonCleanItem.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonCleanItem.setText("Limpar");
        jButtonCleanItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparItem(evt);
            }
        });

        jButtonCancelItem.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonCancelItem.setText("Cancelar");
        jButtonCancelItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CancelItem(evt);
            }
        });

        jButtonConsultItem.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonConsultItem.setText("Consultar");

        javax.swing.GroupLayout jPanelCadastItemLayout = new javax.swing.GroupLayout(jPanelCadastItem);
        jPanelCadastItem.setLayout(jPanelCadastItemLayout);
        jPanelCadastItemLayout.setHorizontalGroup(
            jPanelCadastItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastItemLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanelCadastItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCadastItemLayout.createSequentialGroup()
                        .addComponent(jLabelPrice)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanelCadastItemLayout.createSequentialGroup()
                        .addGroup(jPanelCadastItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelCadastItemLayout.createSequentialGroup()
                                .addComponent(jLabelTitle)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldTitleItem, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonConsultFilm, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelCadastItemLayout.createSequentialGroup()
                                .addComponent(jButtonSaveItem)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonCleanItem)
                                .addGap(179, 179, 179)
                                .addComponent(jButtonCancelItem)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonConsultItem))
                            .addGroup(jPanelCadastItemLayout.createSequentialGroup()
                                .addComponent(jLabelType)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanelCadastItemLayout.setVerticalGroup(
            jPanelCadastItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastItemLayout.createSequentialGroup()
                .addGroup(jPanelCadastItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCadastItemLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanelCadastItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelTitle)
                            .addComponent(jTextFieldTitleItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCadastItemLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonConsultFilm, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32)
                .addGroup(jPanelCadastItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelType)
                    .addComponent(jComboBoxType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanelCadastItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPrice)
                    .addComponent(jTextFieldPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(jPanelCadastItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSaveItem)
                    .addComponent(jButtonCleanItem)
                    .addComponent(jButtonCancelItem)
                    .addComponent(jButtonConsultItem))
                .addContainerGap(87, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelCadastItem, javax.swing.GroupLayout.PREFERRED_SIZE, 796, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addGap(215, 215, 215)
                .addComponent(jLabelCadastItem, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelCadastItem, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelCadastItem, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                            .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(25, 25, 25))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CancelItem(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelItem
        this.dispose();
        this.telaPrincipal.setVisible(true);
    }//GEN-LAST:event_CancelItem

    private void jButtonConsultFilmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultFilmActionPerformed
     ScreenConsultFilm telaConsultaFilme = new ScreenConsultFilm((JFrame) this);
     telaConsultaFilme.setVisible(true);
     this.setVisible(false);
    }//GEN-LAST:event_jButtonConsultFilmActionPerformed

    private void fechar(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_fechar
      this.dispose();
      this.telaPrincipal.setVisible(true);
    }//GEN-LAST:event_fechar

    private void jButtonSaveItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveItemActionPerformed
       String tipo = jComboBoxType.getSelectedItem().toString();
        double preco;
        if(!jTextFieldPrice.getText().isEmpty())
            preco = Double.parseDouble(jTextFieldPrice.getText());
             else 
                preco = 0;
        boolean success = false;
        try{
            ItemController itemController = new ItemController();
            success = itemController.cadastrarItem(this.codFilm, tipo, preco);
             if(success == true){
                JOptionPane.showMessageDialog(null, "O cadastro foi realizado com sucesso!");
                this.limparItem(evt);
                } else {
                    JOptionPane.showMessageDialog(null, "Os dados não foram preechido corretamente");
                
            }

        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "[ERRO:]" + e.getMessage());
        }
    }//GEN-LAST:event_jButtonSaveItemActionPerformed

    private void limparItem(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparItem
       jTextFieldTitleItem.setText("");
       jComboBoxType.setSelectedIndex(0);
       jTextFieldPrice.setText("");
       this.codFilm = 0;
    }//GEN-LAST:event_limparItem

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ScreenItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ScreenItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ScreenItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ScreenItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ScreenItem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton jButtonCancelItem;
    private javax.swing.JButton jButtonCleanItem;
    private javax.swing.JButton jButtonConsultFilm;
    private javax.swing.JButton jButtonConsultItem;
    private javax.swing.JButton jButtonSaveItem;
    private javax.swing.JComboBox<String> jComboBoxType;
    private javax.swing.JLabel jLabelCadastItem;
    private javax.swing.JLabel jLabelPrice;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JLabel jLabelType;
    private javax.swing.JPanel jPanelCadastItem;
    private javax.swing.JTextField jTextFieldPrice;
    private javax.swing.JTextField jTextFieldTitleItem;
    // End of variables declaration//GEN-END:variables
}
